# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-25 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20191022_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='fav_num',
            field=models.IntegerField(default=0, help_text='How many times the product is put in wish list', verbose_name='favorite'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='market_price',
            field=models.FloatField(default=0, help_text='Price in market', verbose_name='market price'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='ship_free',
            field=models.BooleanField(default=True, help_text='True for Free shipping', verbose_name='is free ship'),
        ),
    ]
