# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-10 21:37
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='banner images')),
                ('index', models.IntegerField(default=0, verbose_name='sequence')),
                ('add_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'banner goods',
                'verbose_name_plural': 'banner goods',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sn', models.CharField(default='', max_length=50, verbose_name='SKU')),
                ('name', models.CharField(max_length=100, verbose_name='Goods Name')),
                ('click_num', models.IntegerField(default=0, verbose_name='Clicks')),
                ('sold_num', models.IntegerField(default=0, verbose_name='Sales')),
                ('fav_num', models.IntegerField(default=0, verbose_name='favorite')),
                ('goods_num', models.IntegerField(default=0, verbose_name='stock')),
                ('market_price', models.FloatField(default=0, verbose_name='market price')),
                ('shop_price', models.FloatField(default=0, verbose_name='shop price')),
                ('goods_brief', models.TextField(max_length=500, verbose_name='brief description')),
                ('goods_desc', DjangoUeditor.models.UEditorField(default='', verbose_name='description')),
                ('ship_free', models.BooleanField(default=True, verbose_name='is free ship')),
                ('goods_front_image', models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='front page')),
                ('is_new', models.BooleanField(default=False, verbose_name='is new arrival')),
                ('is_hot', models.BooleanField(default=False, verbose_name='is hot sales')),
                ('add_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'goods',
                'verbose_name_plural': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='category name', max_length=30, verbose_name='Category name')),
                ('code', models.CharField(default='', help_text='Category code', max_length=30, verbose_name='Category code')),
                ('desc', models.TextField(default='', help_text='Category description', verbose_name='Category description')),
                ('category_type', models.IntegerField(choices=[(1, 'First Class'), (2, 'Second Class'), (3, 'Third Class')], help_text='Category class', verbose_name='Category class')),
                ('is_tab', models.BooleanField(default=False, help_text='is on navi bar', verbose_name='On navi-bar')),
                ('add_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='add time')),
                ('parent_category', models.ForeignKey(blank=True, help_text='parent category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Brand name', max_length=30, verbose_name='Brand name')),
                ('desc', models.TextField(default='', help_text='Brand description', max_length=200, verbose_name='Brand desc')),
                ('image', models.ImageField(max_length=200, upload_to='brands/images/')),
                ('add_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='add time')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.GoodsCategory', verbose_name='Goods Category')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brand',
                'db_table': 'goods_goodsbrand',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Images')),
                ('add_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='add time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.Goods', verbose_name='Goods')),
            ],
            options={
                'verbose_name': 'Goods Images',
                'verbose_name_plural': 'Goods Images',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='Goods Category'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='goods'),
        ),
    ]
