# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-06 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20191025_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', max_length=20, verbose_name='Popular Search')),
                ('index', models.IntegerField(default=0, verbose_name='Sorting')),
                ('add_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Added Time')),
            ],
            options={
                'verbose_name': 'Popular Search',
                'verbose_name_plural': 'Popular Search',
            },
        ),
        migrations.CreateModel(
            name='IndexAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='goods.GoodsCategory', verbose_name='Product Categories')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.Goods')),
            ],
            options={
                'verbose_name': 'Product Categories Advertising on HomePage',
                'verbose_name_plural': 'Product Categories Advertising on HomePage',
            },
        ),
    ]
