# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-02 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0004_hotsearchwords_indexad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_star', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'Four Star'), (5, 'Five Star')], default=1, help_text='Rating Star: 1(One Star),2(Two Star),3(Three Star),4(Four Star),5(Five Star)', verbose_name='Product Rating')),
                ('subject', models.CharField(default='', max_length=100, verbose_name='Subject')),
                ('message', models.TextField(default='', help_text='Content', verbose_name='Content')),
                ('add_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'Product Rating',
                'verbose_name_plural': 'Product Rating',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='goods'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
