# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-03 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20191202_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Dislikes'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='reports',
            field=models.IntegerField(default=0, verbose_name='reports'),
        ),
    ]
