# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-03 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20191203_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='reports',
        ),
    ]
