# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-10 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='Goods Quantity')),
                ('add_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Detail',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Order Number')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Transaction Number')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', 'Success'), ('TRADE_CLOSED', 'Timeout'), ('WAIT_BUYER_PAY', 'Transaction Created'), ('TRADE_FINISHED', 'Transaction Completed'), ('PAYING', 'Waiting For Payment')], default='PAYING', max_length=30, verbose_name='Payment Status')),
                ('pay_method', models.CharField(choices=[('PAYPAL', 'PayPal'), ('CREDIT_CARD', 'Credit Card')], default='PAYPAL', max_length=30, verbose_name='Payment Method')),
                ('post_script', models.CharField(max_length=200, verbose_name='Order Comment')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='Order Amount')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='Pay Time')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Shipping Address')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='Receipt')),
                ('singer_mobile', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('add_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField(default=0, verbose_name='Purchase Quantity')),
                ('add_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Add time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='Goods')),
            ],
            options={
                'verbose_name': 'Shopping Cart',
                'verbose_name_plural': 'Shopping Cart',
            },
        ),
    ]
