# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-10 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=100, verbose_name='Province')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('post_code', models.CharField(default='', max_length=100, verbose_name='Post Code')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Detail Address')),
                ('signer_name', models.CharField(default='', max_length=100, verbose_name='Signer')),
                ('signer_mobile', models.CharField(default='', max_length=10, verbose_name='Phone Number')),
                ('add_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'Delivery Address',
                'verbose_name_plural': 'Delivery Address',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'User Favorite',
                'verbose_name_plural': 'User Favorite',
            },
        ),
        migrations.CreateModel(
            name='UserLeavingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(choices=[(1, 'Comment'), (2, 'Complaint'), (3, 'Inquiry'), (4, 'After Sales'), (5, 'Suggestion')], default=1, help_text='Message Type: 1(Comment),2(Complaint),3(Inquiry),4(After Sales),5(Suggestion)', verbose_name='Message Type')),
                ('subject', models.CharField(default='', max_length=100, verbose_name='Subject')),
                ('message', models.TextField(default='', help_text='Content', verbose_name='Content')),
                ('file', models.FileField(help_text='Uploaded File', upload_to='message/images/', verbose_name='Uploaded File')),
                ('add_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'User Comments',
                'verbose_name_plural': 'User Comments',
            },
        ),
    ]
